### ISSUE TITLE
Develop generic literature review checklist

### ISSUE THREAD

**Issue by tareko** [GliaX/meta#2]
Currently:

```
- [ ] Generate search terms
- [ ] [Pubmed](https://www.ncbi.nlm.nih.gov/pubmed/) search
- [ ] Web search for literature
```

Here is the task list for completion of this issue:
- [x] @tareko to develop first draft
- [x] Contact Shelley and Michelle for comment and review
- [ ] Send to external reviewers for comment
  - [ ] Who?
- [ ] Send to group for final comment
- [ ] Commit to wiki
